[project]
name = "lidotiku"
requires-python = ">=3.12, <3.13"
version = "1.5.6"
dependencies = [
    "django~=5.2",
    "pyyaml~=6.0",
    "djangorestframework~=3.16",
    "djangorestframework-camel-case~=1.4",
    "djangorestframework-csv~=3.0",
    "django-cors-headers~=4.8",
    "django-environ~=0.12",
    "django-filter~=25.0",
    "django-helsinki-health-endpoints",
    "django-logger-extra",
    "drf-spectacular",
    "inflection~=0.5",
    "psycopg[c]",
    "sentry-sdk[django]~=2.37",
    "uritemplate~=4.2",
]

[dependency-groups]
dev = [
    "django-stubs~=5.2.5",
    "djangorestframework-stubs~=3.15",
    "pytest-django~=4.11",
    "pytest-cov~=7.0",
    "geopy~=2.4",
    "ipython",
]
prod = [
    "gunicorn~=23.0",
]

[tool.uv]
package = false
exclude-newer = "P3D"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I",
    # pep8-naming
    "N",
    # flake8-bugbear without opinionated rules
    "B0",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
]
[tool.ruff.lint.extend-per-file-ignores]
"*/migrations/*" = ["E501"]
"*/tests/*" = ["E501"]
"api/schemas.py" = ["N815"]
"api/tests/*" = ["N815"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "lidotiku.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
filterwarnings = ["ignore:No directory at:UserWarning"]
