# Generated by Django 4.2 on 2023-07-27 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ecocountercounter",
            table="vw_counters",
        ),
        migrations.AlterModelTable(
            name="ecocounterobservation",
            table="vw_observations",
        ),
    ]
