# Generated by Django 4.2 on 2023-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ecocountercounter_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('classifying', models.BooleanField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('crs_epsg', models.BigIntegerField()),
                ('source', models.CharField(max_length=32)),
                ('geom', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vw_counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=32)),
                ('value', models.BigIntegerField(blank=True)),
                ('unit', models.CharField(max_length=8)),
                ('typeofmeasurement', models.CharField(max_length=32)),
                ('phenomenondurationseconds', models.BigIntegerField()),
                ('vehicletype', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('source', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'vw_observations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EcoCounterCounter',
        ),
        migrations.DeleteModel(
            name='EcoCounterObservation',
        ),
    ]
