# Generated by Django 4.2 on 2023-08-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_counter_observation_delete_ecocountercounter_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='counter',
            table='"lido"."vw_counters"',
        ),
        migrations.AlterModelTable(
            name='observation',
            table='"lido"."vw_observations"',
        ),
    ]
