# Generated by Django 4.2 on 2023-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_counter_table_alter_observation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterWithLatestObservations',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='name')),
                ('source', models.CharField()),
                ('measurement_type', models.CharField(db_column='measurementtype')),
                ('measured_time', models.DateTimeField(db_column='datetime')),
                ('phenomenondurationseconds', models.IntegerField()),
                ('unit', models.CharField()),
                ('value', models.IntegerField()),
                ('counter_updated_at', models.DateField()),
            ],
            options={
                'db_table': '"lido"."vw_counters_with_latest_sensor_observations"',
                'managed': False,
            },
        ),
    ]
