# Generated by Django 4.2.23 on 2025-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_counterwithlatestobservations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datasource",
            fields=[
                (
                    "name",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("description_fi", models.CharField(max_length=255)),
                ("description_sv", models.CharField(max_length=255)),
                ("description_en", models.CharField(max_length=255)),
                ("license", models.CharField(max_length=32)),
            ],
            options={
                "db_table": '"lido"."data_sources"',
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="CounterWithLatestObservations",
        ),
        migrations.AlterModelOptions(
            name="counter",
            options={"managed": False, "ordering": ["id", "source"]},
        ),
    ]
