# Generated by Django 4.2 on 2023-07-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCounterCounter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('classifying', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('crs_epsg', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('geom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EcoCounterObservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=255)),
                ('value', models.IntegerField(blank=True)),
                ('unit', models.CharField(max_length=255)),
                ('typeofmeasurement', models.CharField(max_length=255)),
                ('phenomenondurationseconds', models.IntegerField()),
                ('vehicletype', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
