# [Choice] Python version (use -bullseye variants on local arm64/Apple Silicon): 3, 3.10, 3.9, 3.8, 3.7, 3.6, 3-bullseye, 3.10-bullseye, 3.9-bullseye, 3.8-bullseye, 3.7-bullseye, 3.6-bullseye, 3-buster, 3.10-buster, 3.9-buster, 3.8-buster, 3.7-buster, 3.6-buster
FROM mcr.microsoft.com/vscode/devcontainers/python:3.12-bookworm

ENV PYTHONUNBUFFERED 1

COPY --from=ghcr.io/astral-sh/uv:0.12.1@sha256:cf4eedcaa81655197f625739489effcbe71b61ceb1506f332c3facae5deceded /uv /uvx /usr/local/bin/

RUN apt-get update && apt-get -y install --no-install-recommends postgresql-client gdal-bin

# [Optional] If your requirements rarely change, uncomment this section to add them to the image.
# COPY pyproject.toml uv.lock /tmp/uv-tmp/
# RUN cd /tmp/uv-tmp && uv sync --locked && rm -rf /tmp/uv-tmp

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
