SENSOR_DETAILS = {
    "dataUpdatedTime": "2022-09-26T08:22:24Z",
    "dataLastCheckedTime": "2023-07-28T03:30:01Z",
    "sensors": [
        {
            "id": 5016,
            "name": "OHITUKSET_5MIN_KIINTEA_SUUNTA1",
            "shortName": "kpl/h1",
            "unit": "kpl/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Ajoneuvomäärä suunta 1 (5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Ajoneuvomäärä suunta 1 (5 min)",
        },
        {
            "id": 5019,
            "name": "OHITUKSET_5MIN_KIINTEA_SUUNTA2",
            "shortName": "kpl/h2",
            "unit": "kpl/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Ajoneuvomäärä suunta 2 (5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Ajoneuvomäärä suunta 2 (5 min)",
        },
        {
            "id": 5022,
            "name": "KESKINOPEUS_5MIN_KIINTEA_SUUNTA1",
            "shortName": "km/h1",
            "unit": "km/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Keskinopeus suunta 1 (5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Keskinopeus suunta 1 (5 min)",
        },
        {
            "id": 5025,
            "name": "KESKINOPEUS_5MIN_KIINTEA_SUUNTA2",
            "shortName": "km/h2",
            "unit": "km/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Keskinopeus suunta 2 (5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Keskinopeus suunta 2 (5 min)",
        },
        {
            "id": 5054,
            "name": "OHITUKSET_60MIN_KIINTEA_SUUNTA1",
            "shortName": "kpl/h1",
            "unit": "kpl/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Ajoneuvomäärä suunta 1 (60 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Ajoneuvomäärä suunta 1 (60 min)",
        },
        {
            "id": 5055,
            "name": "OHITUKSET_60MIN_KIINTEA_SUUNTA2",
            "shortName": "kpl/h2",
            "unit": "kpl/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Ajoneuvomäärä suunta 2 (60 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Ajoneuvomäärä suunta 2 (60 min)",
        },
        {
            "id": 5056,
            "name": "KESKINOPEUS_60MIN_KIINTEA_SUUNTA1",
            "shortName": "km/h1",
            "unit": "km/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Keskinopeus suunta 1 (60 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Keskinopeus suunta 1 (60 min)",
        },
        {
            "id": 5057,
            "name": "KESKINOPEUS_60MIN_KIINTEA_SUUNTA2",
            "shortName": "km/h2",
            "unit": "km/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Keskinopeus suunta 2 (60 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Keskinopeus suunta 2 (60 min)",
        },
        {
            "id": 5058,
            "name": "KESKINOPEUS_5MIN_KIINTEA_SUUNTA1_VVAPAAS1",
            "shortName": "LTil1",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennetilanne suunta 1 (5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Liikennetilanne suunta 1 (5 min)",
        },
        {
            "id": 5061,
            "name": "KESKINOPEUS_5MIN_KIINTEA_SUUNTA2_VVAPAAS2",
            "shortName": "LTil2",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennetilanne suunta 2 (5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Liikennetilanne suunta 2 (5 min)",
        },
        {
            "id": 5064,
            "name": "OHITUKSET_5MIN_KIINTEA_SUUNTA1_MS1",
            "shortName": "MTil1",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennemäärä suunta 1 (5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Liikennemäärä suunta 1 (5 min)",
        },
        {
            "id": 5067,
            "name": "OHITUKSET_60MIN_KIINTEA_SUUNTA1_MS1",
            "shortName": "MTil1",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennemäärä suunta 1 (60 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Liikennemäärä suunta 1 (60 min)",
        },
        {
            "id": 5068,
            "name": "OHITUKSET_5MIN_KIINTEA_SUUNTA2_MS2",
            "shortName": "MTil2",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennemäärä suunta 2 (5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Liikennemäärä suunta 2 (5 min)",
        },
        {
            "id": 5071,
            "name": "OHITUKSET_60MIN_KIINTEA_SUUNTA2_MS2",
            "shortName": "MTil2",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennemäärä suunta 2 (60 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Liikennemäärä suunta 2 (60 min)",
        },
        {
            "id": 5116,
            "name": "OHITUKSET_5MIN_LIUKUVA_SUUNTA1",
            "shortName": "kpl/h1",
            "unit": "kpl/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Ajoneuvomäärä suunta 1 (-5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Ajoneuvomäärä suunta 1 (-5 min)",
        },
        {
            "id": 5119,
            "name": "OHITUKSET_5MIN_LIUKUVA_SUUNTA2",
            "shortName": "kpl/h2",
            "unit": "kpl/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Ajoneuvomäärä suunta 2 (-5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Ajoneuvomäärä suunta 2 (-5 min)",
        },
        {
            "id": 5122,
            "name": "KESKINOPEUS_5MIN_LIUKUVA_SUUNTA1",
            "shortName": "km/h1",
            "unit": "km/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Keskinopeus suunta 1 (-5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Keskinopeus suunta 1 (-5 min)",
        },
        {
            "id": 5125,
            "name": "KESKINOPEUS_5MIN_LIUKUVA_SUUNTA2",
            "shortName": "km/h2",
            "unit": "km/h",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Keskinopeus suunta 2 (-5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Keskinopeus suunta 2 (-5 min)",
        },
        {
            "id": 5158,
            "name": "KESKINOPEUS_5MIN_LIUKUVA_SUUNTA1_VVAPAAS1",
            "shortName": "LTila1",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennetilanne suunta 1 (-5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Liikennetilanne suunta 1 (-5 min)",
        },
        {
            "id": 5161,
            "name": "KESKINOPEUS_5MIN_LIUKUVA_SUUNTA2_VVAPAAS2",
            "shortName": "LTila2",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennetilanne suunta 2 (-5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Liikennetilanne suunta 2 (-5 min)",
        },
        {
            "id": 5164,
            "name": "OHITUKSET_5MIN_LIUKUVA_SUUNTA1_MS1",
            "shortName": "MTila1",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennemäärä suunta 1 (-5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Liikennemäärä suunta 1 (-5 min)",
        },
        {
            "id": 5168,
            "name": "OHITUKSET_5MIN_LIUKUVA_SUUNTA2_MS2",
            "shortName": "MTila2",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Liikennemäärä suunta 2 (-5 min)",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Liikennemäärä suunta 2 (-5 min)",
        },
        {
            "id": 6001,
            "name": "SUUNTA1",
            "shortName": "Suun1",
            "unit": "Nimi",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Suunnassa 1 oleva ISO kaupunki/paikkakunta",
                "sv": "null",
                "en": "null",
            },
            "direction": "INCREASING_DIRECTION",
            "description": "Suunnassa 1 oleva ISO kaupunki/paikkakunta",
        },
        {
            "id": 6002,
            "name": "SUUNTA2",
            "shortName": "Suun2",
            "unit": "Nimi",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Suunnassa 2 oleva ISO kaupunki/paikkakunta",
                "sv": "null",
                "en": "null",
            },
            "direction": "DECREASING_DIRECTION",
            "description": "Suunnassa 2 oleva ISO kaupunki/paikkakunta",
        },
        {
            "id": 60000,
            "name": "TILA",
            "shortName": "Tila",
            "unit": "***",
            "accuracy": "null",
            "sensorValueDescriptions": [
                {"descriptionEn": "OK", "descriptionFi": "OK", "sensorValue": 0.0},
                {
                    "descriptionEn": "Suspected malfunction",
                    "descriptionFi": "Vikaepäily",
                    "sensorValue": 1.0,
                },
                {
                    "descriptionEn": "Confirmed malfunction",
                    "descriptionFi": "Vika vahvistettu",
                    "sensorValue": 2.0,
                },
                {
                    "descriptionEn": "Confirmed malfunction, repair not planned in near future",
                    "descriptionFi": "Vika vahvistettu, mutta ei korjata lähiaikoina",
                    "sensorValue": 3.0,
                },
                {
                    "descriptionEn": "Maintenance request sent",
                    "descriptionFi": "Huolto tilattu",
                    "sensorValue": 4.0,
                },
                {
                    "descriptionEn": "Maintenance work done",
                    "descriptionFi": "Huolto tehty",
                    "sensorValue": 5.0,
                },
                {
                    "descriptionEn": "Maintenance work interrupted",
                    "descriptionFi": "Huolto keskeytetty",
                    "sensorValue": 6.0,
                },
            ],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Aseman tila laatutietojärjestelmässä. 0=OK",
                "sv": "null",
                "en": "null",
            },
            "direction": "UNKNOWN",
            "description": "Aseman tila laatutietojärjestelmässä. 0=OK",
        },
        {
            "id": 60002,
            "name": "KERUUTILA",
            "shortName": "A_KER",
            "unit": "null",
            "accuracy": "null",
            "sensorValueDescriptions": [],
            "presentationNames": {"fi": "null", "sv": "null", "en": "null"},
            "descriptions": {
                "fi": "Aseman keruutila: Katso arvovastineet-taulusta",
                "sv": "null",
                "en": "null",
            },
            "direction": "UNKNOWN",
            "description": "Aseman keruutila: Katso arvovastineet-taulusta",
        },
    ],
}
