name: release-please
on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/release-please.yml@main
